name: seminar_booking_app
description: A comprehensive seminar hall booking application for Poornima University.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.9.4

  # State Management & Routing
  provider: ^6.1.2
  go_router: ^14.2.0

  # UI & Styling
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.7296
  badges: ^3.1.2

  # Utility
  intl: ^0.19.0
  collection: ^1.18.0
  url_launcher: ^6.3.0
  fl_chart: ^0.68.0
  table_calendar: ^3.1.1
  cloud_functions: ^4.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/images/logo.png

flutter_launcher_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true