name: seminar2
description: A Flutter app for booking seminar halls at Poornima University.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1

  # Routing
  go_router: ^12.1.1

  # Local Storage
  shared_preferences: ^2.2.2

  # UI & Styling
  google_fonts: ^6.1.0
  material_design_icons_flutter: ^7.0.7296
  
  # Charts & Calendar
  fl_chart: ^0.64.0
  table_calendar: ^3.0.9

  # Utility
  intl: ^0.18.1
  collection: ^1.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true